### ISSUE TITLE
Consider changing successors to go upward in the hierarchy too

### ISSUE THREAD

**Issue by jonsterling** [paolobrasolin/jekyll-sheafy#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Original problem

The prev/next functionality is really useful! One thing I was thinking is that it could be made more useful by changing its semantics for the case when you are looking at the final subnode of a particular branch. Just to say, I believe that the current behavior is in line with how the Stacks Project works, so what I am proposing is a deviation from the Stacks Project semantics.

As an example, this node (https://www.jonmsterling.com/math/nodes/002L.html) does not have a successor, because it is the last node in its branch.

### Proposed solution

I think the reader would appreciate it greatly if the next node were the successor of its parent, namely https://www.jonmsterling.com/math/nodes/000N.html. This would allow readers to just click "next next next" from the beginning until the end, no matter how far they drilled down. What do you think?

### Alternatives considered

One alternative is to provide a "go up" button when there is no successor. This has the advantage of not changing the semantics and staying aligned with the Stacks Project, but I think the downside is the it makes the reader need to click more in order to read the book.

Finally there is a potential middle ground, that may be harder to implement. We could keep the successor semantics, but change the user interface to have an "up and to the right" button that does the described thing, in case there is no successor node. This would also be fine with me if you think it is better!

### Additional context

<img width="767" alt="image" src="https://user-images.githubusercontent.com/55057/152131385-a1963a53-37c8-4df7-85b5-546a08c4b5cf.png">

**Comment by paolobrasolin** [comment]
Thanks for the suggestion! :heart: 

> This would allow readers to just click "next next next" from the beginning until the end, no matter how far they drilled down. What do you think?

Let's break this down. Consider this TOC:
```
- 1
  - 1.1
    - 1.1.1
    - 1.1.2
    - 1.1.3
  - 1.2
  - 1.3
- 2
  - 2.1
  - 2.2
- 3
  - 3.1
```

I can think of four behaviours for "transversal by clicking":

```
A: 1.1.1 > 1.1.2 > 1.1.3
B: 1.1.1 > 1.1.2 > 1.1.3 ^ 1.1 > 1.2 > 1.3 ^ 1   > 2   > 3
C: 1.1.1 > 1.1.2 > 1.1.3 / 1.2 > 1.3 / 2   > 3
D: 1.1.1 > 1.1.2 > 1.1.3 > 1.2 > 1.3 > 2   > 2.1 > 2.2 > 3 > 3.1
```

* `A` is the current one. You only have left/right buttons and you get stuck at the end of branches. Whoops.
* `B` is the alternative you propose. You have left/up/right buttons. At the end of branches you click up, then right. Better.
* `C` is the middle ground you propose. At the end of branches the right button becomes "up-right" and you just click it. Faster.
* `D` just follows the TOC as a list and makes no sense to me. Why would you want to visit `2.1` after already seeing it embedded in `2`? :man_shrugging:

I implemented `B` at the beginning, with the up button always visibe, and discarded it just because the layout was clunky. It's not a bad UI, though. Very transparent, and a bit reminiscent of 90s internet (in a good way).

Both `B` and `C` sound fine to me, but I'd rather not change the semantics of the `successors` and `predecessors` variables. Maybe that's bad naming (do you think it is?), but I deliberately chose it to be just about siblings. This way `A`, `B` and `C` are resp. trivial, trivial and simple to implement at layout level. If we make it about a specific kind of tree transversal (`C`) then `C` becomes trivial to implement at the layout level while making `A` and `B` messier.

So: I'd rather not change the data structure because `C` can be done at the template level: (sorry for the metacode)
> **IF** `node.successors.first` is present **THEN** link it and draw a right-arrow **ELSE** get the first element of `node.ancestors.reversed` which has a nonempty `successors.first` and link it drawing an up-right-arrow **END**

If you confirm that `C` is what you want I'll make a PR to [jonsterling/math](https://github.com/jonsterling/math/) with it. :wink:

**Comment by paolobrasolin** [comment]
Here it is: jonsterling/math#57
